name = "danganronpa-rebirth-rp-bot"
main = "worker.js"
compatibility_date = "2024-11-01"

[vars]
GITHUB_OWNER = "Katsu6624"
GITHUB_REPO = "danganronpa-rebirth-rp"
GITHUB_BRANCH = "master"
DISCORD_GUILD_ID = "1178733678080294963"
DISCORD_ROLE_ESPOIR = "1185366817359790080"
DISCORD_ROLE_PREPA = "1178869069823344672"
DISCORD_CHANNEL_INSCRIPTION = ""

# Secrets (ne jamais mettre en clair ici) : à définir avec :
#   wrangler secret put DISCORD_PUBLIC_KEY
#   wrangler secret put GITHUB_TOKEN
#   wrangler secret put DISCORD_BOT_TOKEN
